### ISSUE TITLE
Android: advanceLastReadMessageIndexWithResult with error: java.lang.Integer cannot be cast to java.lang.Long

### ISSUE THREAD

**Issue by bull-xu** [Diversido/flutter_twilio_conversations#39]
The advanceLastReadMessageIndexWithResult API seems has a wrong type with ClassCastException on Android:
```
D/TwilioInfo(26449): TwilioConversationsPlugin.onMethodCall => received Messages#advanceLastReadMessageIndexWithResult
E/MethodChannel#flutter_twilio_conversations(26449): Failed to handle method call
E/MethodChannel#flutter_twilio_conversations(26449): java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
E/MethodChannel#flutter_twilio_conversations(26449): 	at twilio.flutter.twilio_conversations.methods.MessagesMethods.advanceLastReadMessageIndexWithResult(MessagesMethods.kt:302)
E/MethodChannel#flutter_twilio_conversations(26449): 	at twilio.flutter.twilio_conversations.PluginHandler.onMethodCall(PluginHandler.kt:85)
E/MethodChannel#flutter_twilio_conversations(26449): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#flutter_twilio_conversations(26449): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/MethodChannel#flutter_twilio_conversations(26449): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#flutter_twilio_conversations(26449): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
E/MethodChannel#flutter_twilio_conversations(26449): 	at android.os.Handler.handleCallback(Handler.java:958)
E/MethodChannel#flutter_twilio_conversations(26449): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#flutter_twilio_conversations(26449): 	at android.os.Looper.loopOnce(Looper.java:205)
E/MethodChannel#flutter_twilio_conversations(26449): 	at android.os.Looper.loop(Looper.java:294)
E/MethodChannel#flutter_twilio_conversations(26449): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/MethodChannel#flutter_twilio_conversations(26449): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_twilio_conversations(26449): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/MethodChannel#flutter_twilio_conversations(26449): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by martintrollip** [comment]
@bull-xu thanks for reporting this
