### ISSUE TITLE
Exception when participant is removed from conversation

### ISSUE THREAD

**Issue by ChasakisD** [Diversido/flutter_twilio_conversations#9]
It seems that in [ChatListener](https://github.com/Diversido/flutter_twilio_conversations/blob/main/android/src/main/kotlin/twilio/flutter/twilio_conversations/listeners/ChatListener.kt) the onConversationDeleted is not implemented.

The stacktrace:
```
com.twilio.conversations.ListenerException: Exception thrown by a listener. Your application might have a problem in listener implementation. Listeners must never throw uncaught exceptions. See 'Caused by:' below for more details.
E/AndroidRuntime( 6501): 	at java.lang.reflect.Constructor.newInstance0(Native Method)
E/AndroidRuntime( 6501): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
E/AndroidRuntime( 6501): 	at com.twilio.conversations.internal.RethrowingForwarder$RethrowingProxy.invoke(RethrowingForwarder.java:123)
E/AndroidRuntime( 6501): 	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
E/AndroidRuntime( 6501): 	at $Proxy4.onConversationDeleted(Unknown Source)
E/AndroidRuntime( 6501): 	at com.twilio.conversations.internal.ConversationsClientListenerForwarder$4.onNotify(ConversationsClientListenerForwarder.java:133)
E/AndroidRuntime( 6501): 	at com.twilio.conversations.internal.ConversationsClientListenerForwarder$1.run(ConversationsClientListenerForwarder.java:81)
E/AndroidRuntime( 6501): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime( 6501): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 6501): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime( 6501): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime( 6501): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/AndroidRuntime( 6501): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6501): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime( 6501): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/AndroidRuntime( 6501): Caused by: kotlin.NotImplementedError: An operation is not implemented: Not yet implemented
E/AndroidRuntime( 6501): 	at twilio.flutter.twilio_conversations.listeners.ChatListener.onConversationDeleted(ChatListener.kt:108)
E/AndroidRuntime( 6501): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6501): 	at com.twilio.conversations.internal.RethrowingForwarder$RethrowingProxy.invoke(RethrowingForwarder.java:121)
E/AndroidRuntime( 6501): 	... 12 more
```

Edit: As I can see, there is a [PR](https://github.com/Diversido/flutter_twilio_conversations/pull/8) that addresses this issue, but I dont think that there is a release for that right?

**Comment by martintrollip** [comment]
There is no release yet.  @asmodeoux what is the process to create a release, since there was a few fixes since `1.0.0`?

**Comment by asmodeoux** [comment]
@martintrollip you're right, actually I though pub.dev fetches the latest updates from GitHub itself but I had to manually publish the changes. Done now, enjoy version `1.1.0` and feel free to close this if the issue is confirmed to be fixed ✅

**Comment by martintrollip** [comment]
Thanks for the quick update

**Comment by ChasakisD** [comment]
This is fixed! Thank you very much!
